[#e2,reftext=E.2]
=== (E.2) Components

ifdef::env-draft[]
TIP: _List of elements of the environment that may affect or be affected by the system and project. It includes other systems to which the system must be interfaced. These components may include existing systems, particularly software systems, with which the system will interact — by using their APIs (program interfaces), or by providing APIs to them, or both. These are interfaces provided to the system from the outside world. They are distinct from both: interfaces provided by the system to the outside world (<<s3>>); and technology elements that the system's development will require (<<p5>>)._  <<BM22>>
endif::[]

The system will interact with the following external component(s)

*Kinect Sensor:* This component is responsible for delivering the system live .pcd data for the detection algorithm to run on.

*Detection Algorithm* This component will be used to handle all of the image processing related to being able to detect a person.

*.pcd Processor* This component will be used in our code to aid the processing of .pcd files, and further help the detection algorithm in person detection.
