[#e3,reftext=E.3]
=== (E.3) Constraints

ifdef::env-draft[]
TIP: _Obligations and limits imposed on the project and system by the environment. This chapter defines non-negotiable restrictions coming from the environment (business rules, physical laws, engineering decisions), which the development will have to take into account._  <<BM22>>
endif::[]

- *Location of kinect sensor*: If the kinect sensor was placed outdoors, it could introduce unstable lighting and different weather conditions can prevent the microsoft kinect from capturing reliable data. Making the detection software work in outdoor environments can pose additionally challenges which is uncessary as the software is meant for indoor assistive robots. Therefore, the scope of our project will be limited to exclusively indoor use. 

- *Lighting Levels*: If the kinect sensor is placed in a room that is too dark or too bright, it can prevent the detection software from functioning correctly. Modifying the detection software to detect in the dark without color data proposes additional challenges beyond the scope of the project. Therefore, the kinect must be placed in a room with ample but not excessive lighting unless the development team has enough time during the development period to work on the stretch goal that is detecting humans in the dark.

