[#g1,reftext=G.1]
=== (G.1) Context and Overall Objectives

ifdef::env-draft[]
TIP: _High-level view of the project: organizational context and reason for building a system. It explains why the project is needed, recalls the business context, and presents the general business objectives._  <<BM22>>
endif::[]

Currently within robotics at McMaster, pushing forward the use of robots with computer vision is a main objective. With the current technology, there is apt ability for the robots to detect obstacles and avoid them. With this project, we aim to fill the afformentioned gap and provide an algorithm to equip these robots with the ability to detect people, with a specific focus on partially detected people, in real time. This project will be used by graduate students and professors in the Mechanical Engineering lab for future research projects.

Specifically, our goals for this project are to detect partially detected people in real time. This can be broken up into a few sub-goals as follows. First, we need to ensure that we can detect people. This is imperative for our our POC demo, in which we want to be able to properly detect people outside of cover. After this, we need to map a person, and their body parts, to shapes. This lays down the groundwork for the ability to detect partially covered people, through figuring outt which body part is showing. We also need to ensure that our output includes location data, i.e. the precise coordinates of the detected human. Additionally, we need to ensure that we are able to process and produce these outputs in real-time. Finally, along with the ability to process PCD data live from a kinect, we need to be able to process raw PCD files offline. 