[#g2,reftext=G.2]
=== (G.2) Current situation

ifdef::env-draft[]
TIP: _Current state of processes to be addressed by the project and the resulting system. It describes the current situation, upon which the system is expected to improve_  <<BM22>>
endif::[]

The current state of robotics research, specifically at McMaster, does not include the ability to process Kinect sensor data, or .pcd file, and detect what is a human versus an obstacle on screen. Regarding robots using computer vision sensors, the current situation is that they have the ability to detect obstacles as well as the ability to stop moving upon detecting an obstacle in the robot's path. As mentioned in the Overall Objectives section, this creates a gap where we are unable to differentiate humans from obstacles, as humans are currently considered the same as an obstacle: something that is blocking the robot's path. In order to proceed with more robust options for research with these robots, especially regarding interactions between robots and humans, there must be some way for the robot to detect humans apart from random obstacles for safety concerns or to perform certain actions. Additionally, the ability to take in PCD data and detect not just humans, but specific body parts, the research applications that may spawn from this widen significantly.
