[#p5,reftext=P.5]
=== (P.5) Required technology elements

ifdef::env-draft[]
TIP: _External systems, hardware and software, expected to be necessary for building the system. It lists external technology elements, such as program libraries and hardware devices, that the project is expected to require. Although the actual use of such products belongs to design and implementation rather than requirements, it is part of the requirements task to identify elements whose availability is critical to the success of the project — an important element of risk analysis (<<p6>>)._  <<BM22>>
endif::[]

- *Point Cloud Library* : The point cloud library provides a library of algorithms for 3D geometry and point cloud processing. This is essential for working with point cloud data.
- *Eigen Library* : The eigen library provides a linear algebra framework for C++ necessary to perform required computations.
- *Microsoft Kinect* : The microsoft kinect is necessary for producing usable data that can be analyzed. 
- *Kinect2Grabber* : Kinect2Grabber is a provided tool that retrieves point cloud data from a Kinect v2 into PCL.